version: '2'
services:
  jenkins:
    tty: true
    image: jenkins-ci-master
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins-ci-master
    build: ./
    volumes:
      - ci_repo:/var/jenkins_home

volumes:
  ci_repo:
    driver: local


